# Generated by Django 2.1.2 on 2018-12-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20181225_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_location',
            field=models.CharField(max_length=400),
        ),
    ]
